openapi: 3.1.0
info:
  title: NubemFeast Analysis API
  version: 1.0.0
  description: API para análisis de accesibilidad con Vision AI

paths:
  /api/scans/{scan_id}/analyze:
    parameters:
      - name: scan_id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    post:
      summary: Iniciar análisis de accesibilidad
      operationId: startAnalysis
      tags:
        - Analysis
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalysisRequest'
      responses:
        '202':
          description: Análisis iniciado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResponse'
        '400':
          description: No hay imágenes para analizar
        '404':
          description: Scan no encontrado
        '409':
          description: Análisis ya en progreso

  /api/scans/{scan_id}/analysis:
    parameters:
      - name: scan_id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: Obtener resultado del análisis
      operationId: getAnalysis
      tags:
        - Analysis
      responses:
        '200':
          description: Resultado del análisis
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisDetailResponse'
        '404':
          description: Scan o análisis no encontrado

  /api/scans/{scan_id}/analysis/barriers:
    parameters:
      - name: scan_id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: Listar todas las barreras detectadas
      operationId: listBarriers
      tags:
        - Analysis
      parameters:
        - name: severity
          in: query
          schema:
            $ref: '#/components/schemas/BarrierSeverity'
        - name: type
          in: query
          schema:
            $ref: '#/components/schemas/BarrierType'
      responses:
        '200':
          description: Lista de barreras
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BarrierResponse'
        '404':
          description: Scan no encontrado

  /api/images/{image_id}/barriers:
    parameters:
      - name: image_id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: Listar barreras de una imagen específica
      operationId: getImageBarriers
      tags:
        - Analysis
      responses:
        '200':
          description: Lista de barreras de la imagen
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BarrierResponse'
        '404':
          description: Imagen no encontrada

components:
  schemas:
    AnalysisRequest:
      type: object
      properties:
        wheelchair_profile_id:
          type: string
          format: uuid
          description: ID del perfil de silla de ruedas (opcional, usa default si no se especifica)
        force:
          type: boolean
          default: false
          description: Forzar re-análisis aunque ya exista uno completado

    AnalysisStatus:
      type: string
      enum:
        - pending
        - in_progress
        - completed
        - failed

    AnalysisResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        scan_id:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/AnalysisStatus'
        started_at:
          type: string
          format: date-time
          nullable: true
        completed_at:
          type: string
          format: date-time
          nullable: true
        error_message:
          type: string
          nullable: true
        total_images_analyzed:
          type: integer
        total_barriers_found:
          type: integer
        accessibility_score:
          type: number
          minimum: 0
          maximum: 100
          nullable: true

    AnalysisDetailResponse:
      allOf:
        - $ref: '#/components/schemas/AnalysisResponse'
        - type: object
          properties:
            barriers_by_severity:
              type: object
              properties:
                low:
                  type: integer
                medium:
                  type: integer
                high:
                  type: integer
                critical:
                  type: integer
            barriers_by_type:
              type: object
              additionalProperties:
                type: integer
            images_with_barriers:
              type: array
              items:
                $ref: '#/components/schemas/ImageAnalysisSummary'

    ImageAnalysisSummary:
      type: object
      properties:
        image_id:
          type: string
          format: uuid
        image_url:
          type: string
          format: uri
        sequence_order:
          type: integer
        barrier_count:
          type: integer
        max_severity:
          $ref: '#/components/schemas/BarrierSeverity'
          nullable: true

    BarrierType:
      type: string
      enum:
        - step
        - stairs
        - narrow_door
        - narrow_passage
        - steep_ramp
        - uneven_surface
        - obstacle
        - heavy_door
        - revolving_door
        - threshold
        - gravel
        - grass
        - slope
        - other

    BarrierSeverity:
      type: string
      enum:
        - low
        - medium
        - high
        - critical

    BarrierResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        image_id:
          type: string
          format: uuid
        barrier_type:
          $ref: '#/components/schemas/BarrierType'
        severity:
          $ref: '#/components/schemas/BarrierSeverity'
        description:
          type: string
        bbox_x:
          type: number
          minimum: 0
          maximum: 1
          nullable: true
        bbox_y:
          type: number
          minimum: 0
          maximum: 1
          nullable: true
        bbox_width:
          type: number
          minimum: 0
          maximum: 1
          nullable: true
        bbox_height:
          type: number
          minimum: 0
          maximum: 1
          nullable: true
        estimated_width_cm:
          type: number
          nullable: true
        estimated_height_cm:
          type: number
          nullable: true
        estimated_depth_cm:
          type: number
          nullable: true
        recommendation:
          type: string
          nullable: true
        confidence:
          type: number
          minimum: 0
          maximum: 1
