name: 🐛 Bug Report
description: Reportar un error
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: Describe el bug claramente
      placeholder: Qué está pasando...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      description: Cómo reproducir el error
      placeholder: |
        1. Ir a '...'
        2. Hacer click en '...'
        3. Ver error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento esperado
      description: Qué debería pasar
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Entorno
      options:
        - Local
        - Staging
        - Production
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Screenshots
      description: Añade logs o capturas si ayudan
